name: Hello World FastAPI Application
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: A FastAPI Hello World Docker image
      run: docker build -t '${{secrets.DOCKER_USERNAME}}'/fastapi-helloworld-app:latest' .
      
    - name: Login to docker
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.DOCKER_USERNAME}}'/fastapi-helloworld-app:latest'